services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mynetwork

  app:
    build: .
    volumes:
      - .:/usr/src/app # Monta o diretório do projeto como volume
      - /usr/src/app/node_modules # Evita que os node_modules locais sobrescrevam os do contêiner
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
